### ISSUE TITLE
Crosslink VIP example - Incorrect device ID

### ISSUE THREAD

**Issue by siliconwitch** [gatecat/prjoxide#18]
Discovered an error while testing with the VIP sensor board. The device ID in the [Makefile](https://github.com/gatecat/prjoxide/blob/master/examples/blinky_vip/Makefile) needed to be changed to `LIFCL-40-8BG400`.

Strange because the chip physically says CES on it, but using `LIFCL-40-8BG400CES` didn't work either.

**Comment by siliconwitch** [comment]
A picture of the board I tested with. We have two of these, recently bought from Digikey.

![tempImage0eDK9q](https://user-images.githubusercontent.com/7815190/137871689-f1cec1d6-4323-43b1-b3b2-c719548d5fca.gif)

**Comment by gatecat** [comment]
This looks like ES2 silicon which has a production IDCODE. I will investigate and add this as an option (my board is ES1 with the ES IDCODE)
