### ISSUE TITLE
Failed to load chipdb 'nexus/chipdb-LIFCL.bin'

### ISSUE THREAD

**Issue by Noxet** [gatecat/prjoxide#47]
I am trying to build a project for a CrossLink-NX device.
The following is being executed by the makefile:

```
pushd /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes && nextpnr-nexus --placer-heap-timingweight 60 -l /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes_nextpnr.log --device LIFCL-40-9BG256C --pdc /home/noxet/dev/sdi-mipi-video-converter-fpga-design/constraints/video_converter_3g-2lanes.pdc --json /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes.json --fasm /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes.fasm && popd
~/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes ~/dev/sdi-mipi-video-converter-fpga-design
ERROR: Failed to load chipdb 'nexus/chipdb-LIFCL.bin'
```

I have built prjoxide from master, and I currently have version 0.1. I cloned the repo recursively.
I also followed the instruction for building nextpnr-nexus.

I do not know how to progress here. Am I missing something?
Thanks

**Comment by gatecat** [comment]
Please can you provide a bit of information about your build environment (operating system, exact nextpnr cmake arguments)?

In case you are okay using prebuilt tools, another option is to use the [oss-cad-suite](https://github.com/YosysHQ/oss-cad-suite-build/) binaries. But if you prefer to build it yourself, that's also fine and I'll be happy to help you get it working.

**Comment by Noxet** [comment]
Sure.
OS: Ubuntu 22.04

I installed prjoxide:
```
git clone --recursive https://github.com/gatecat/prjoxide
cd libprjoxide
cargo install --path prjoxide
```
 and then nextpnr with: `cmake -DARCH=nexus -DOXIDE_INSTALL_PREFIX=$HOME/.cargo ..` in the build folder.

Then, in the project I am trying to build (an OSS project), when running the makefile I get this output:
```
pushd /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes && nextpnr-nexus --placer-heap-timingweight 60 -l /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes_nextpnr.log --device LIFCL-40-9BG256C --pdc /home/noxet/dev/sdi-mipi-video-converter-fpga-design/constraints/video_converter_3g-2lanes.pdc --json /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes.json --fasm /home/noxet/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes/1080p_3g-2lanes.fasm && popd
~/dev/sdi-mipi-video-converter-fpga-design/build/1080p_3g-2lanes ~/dev/sdi-mipi-video-converter-fpga-design
ERROR: Failed to load chipdb 'nexus/chipdb-LIFCL.bin'
```

**Comment by gatecat** [comment]
Have you tried a fully clean build deleting the cmake build folder and trying again?

**Comment by gatecat** [comment]
Another thing to check is that nothing went wrong during the build process. Can you confirm that after a build:

 - there's a file `nexus/chipdb-LIFCL.cc` generated inside the build folder 
 
 - the last two lines of that file (it will mostly be a very long blob of data in a string) are:
 ```
 EmbeddedFile chipdb_file_LIFCL("nexus/chipdb-LIFCL.bin", chipdb_blob_LIFCL);
NEXTPNR_NAMESPACE_END
 ```

**Comment by Noxet** [comment]
I did a clean build and everything is fine. I realized that I probably forgot to run make install after I got a working build last time... Thank you for your time!
